In [5]:
#Using numerical NUMPY
import numpy as np

In [6]:
m=np.array([[7,8,9],[10,11,12]])

m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
m.shape


(2, 3)

In [ ]:
#arange returns evenly spaced values within a given interval
n=np.arange(0,30,2) #start at 0 count up to 2
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
#reshape change the grid layout without altering the total element count or original data
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
lspace=np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#ones returns a new array og given shape and type filled with ones
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#eye returns a 2D array witrh ones on the diagonal and zeros eleswhere
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#numpy.diag() function

In [19]:
#matrix creation by array input
num=np.matrix(([11,121,130],[613,30,20],[589,22,81]))

In [20]:
type(num)

numpy.matrix

In [21]:
print("Main diagonal elements : \n",np.diag(num))
print("\n Daigonal elements above main diagonal : \n",np.diag(num,1))
print("\n Daigonal elements below main diagonal : \n",np.diag(num,-1))
print("\n Daigonal elements one step above main diagonal : \n",np.diag(num,2))
print("\n Daigonal elements one step below main diagonal : \n",np.diag(num,-2))

Main diagonal elements : 
 [11 30 81]

 Daigonal elements above main diagonal : 
 [121  20]

 Daigonal elements below main diagonal : 
 [613  22]

 Daigonal elements one step above main diagonal : 
 [130]

 Daigonal elements one step below main diagonal : 
 [589]


In [22]:
#create an array using repeating list
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
#repeat elements of an array using repeat
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [27]:
p=np.ones([2,5],int)

In [32]:
#stack array squence vertically
np.vstack([p,2*p])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [31]:
#stack array in squence hortizontally
np.hstack([p,2*p])

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 2, 2, 2, 2, 2]])

In [33]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [34]:
print(x+y) #element wise addition
print(x-y) #substraction
print(x*y) #multiplication
print(x/y) #division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [35]:
print(x**2) #element wise power
print(x@y) #dot product 1*4 + 2*5 +3*6 = 32

[1 4 9]
32


In [37]:
#dot product:
x.dot(y)

np.int64(32)

In [38]:
A=np.array([7,8,9])
B=np.array([3,9,12])

In [39]:
print(A+B) #element wise addition
print(A-B) #substraction
print(A*B) #multiplication
print(A/B) #division
print(A**2) #element wise power
print(A@B) #dot product 

[10 17 21]
[ 4 -1 -3]
[ 21  72 108]
[2.33333333 0.88888889 0.75      ]
[49 64 81]
201


In [40]:
z=np.array([y,2*y])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [45]:
print(len(z)) # gives the number of rows

2


In [46]:
#the shape of the array
z.shape

(2, 3)

In [47]:
#use.T to get transpose 
z.T


array([[ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [48]:
z.T.shape

(3, 2)

In [ ]:
z.dtype  # use .dtype to see the data type of the elements of the array

dtype('int64')

In [53]:
# use .astype to cast to a specific type
z=z.astype('f')
z.dtype

dtype('float32')

In [58]:
# using the NUMPY built in math functions
a=np.array([-4,-2,1,3,5])
a.sum()

np.int64(3)

In [ ]:
a.max() # find the max value

np.int64(5)

In [60]:
a.min()

np.int64(-4)

In [61]:
a.mean()

np.float64(0.6)

In [62]:
a.std()

np.float64(3.2619012860600183)

In [64]:
#argmax AND argmin return the index of the maximum and minimum values in the array
a.argmax()

np.int64(4)

In [65]:
a.argmin()

np.int64(0)

In [77]:
#EXAMPLE 2
x=np.array([7,3,-2,0,100,25])

In [78]:
x.sum()

np.int64(133)

In [79]:
x.max()


np.int64(100)

In [80]:
x.min()

np.int64(-2)

In [81]:
x.mean()

np.float64(22.166666666666668)

In [82]:
x.std()


np.float64(35.91386299962113)

In [83]:
x.argmax()

np.int64(4)

In [84]:
x.argmin()

np.int64(2)

In [85]:
s=np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [86]:
#indexing and slicing
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
s[0],s[4],s[-1]     #use bracket to get at a specific index

(np.int64(0), np.int64(16), np.int64(25))

In [90]:
s[1:5]         # use : to indicate a range  that is array[start:stop]

array([ 1,  4,  9, 16])

In [91]:
s=np.arange(13)**2
s


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [92]:
s[0],s[-4]

(np.int64(0), np.int64(81))

In [93]:
s[-4:]     # use negative to count from the back

array([ 81, 100, 121, 144])

In [95]:
s[-5::-2]          #array[start:stop:stepsize]

array([64, 36, 16,  4,  0])

In [96]:
s[-5:-2]

array([ 64,  81, 100])

In [97]:
r=np.arange(100)
r.resize(10,10)
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
r[3,4]      #returning element from multidimentional array

np.int64(34)

In [100]:
r[2,1:4]

array([21, 22, 23])

In [101]:
r[3,3:6]

array([33, 34, 35])

In [102]:
r[:3,:-1] #here we are selecting all the rows upto slected row and column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])