1. #Create a constant array
	Prints "[[ 7.  7.]
              [ 7.  7.]]"


In [6]:
import numpy as np

In [7]:
x=np.full((2,2),7.0)    #np.full() is a NumPy function used to create an array where every element has the same value
x

array([[7., 7.],
       [7., 7.]])

2. Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

In [8]:
y=np.random.random((2, 2))     #np.random.random() uses NumPy’s random module to generate random floating-point values between 0 and 1.
y

array([[0.70604231, 0.12457148],
       [0.59312947, 0.58423361]])

3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array
Number of elements
Shape
Dimension
Data type

In [10]:
A= np.arange(10, 50)

print("Array:", A)
print("Number of elements:", A.size)
print("Shape:", A.shape)
print("Dimension:", A.ndim)
print("Data type:", A.dtype)

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Number of elements: 40
Shape: (40,)
Dimension: 1
Data type: int64


4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [11]:
A=np.zeros(10)
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
B=np.ones([3,3])
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
id=np.eye(4)
id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
numbers = np.arange(5, 51, 5)
numbers

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4

Display the shape and ndim of each result.

In [15]:
x=np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
y=x.reshape(4,6)
print(y)
print(y.shape)
print(y.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)
2


In [17]:
z=x.reshape(6,4)
print(z)
print(z.shape)
print(z.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)
2


In [18]:
s=x.reshape(2,3,4)
print(s)
print(s.shape)
print(s.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
3


6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element
Last element
Third element
First four elements
Last three elements

In [19]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
marks

array([78, 85, 92, 67, 88, 73, 95, 81])

In [20]:
marks[0]

np.int64(78)

In [21]:
marks[-1]

np.int64(81)

In [22]:
marks[2]

np.int64(92)

In [23]:
marks[:4]

array([78, 85, 92, 67])

In [24]:
marks[-3:]

array([73, 95, 81])

7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b
a - b
a * b
a / b
Square of every element in a

In [25]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

In [26]:
print(a+b)

[15 30 45 60 75]


In [27]:
print(a-b)

[ 5 10 15 20 25]


In [28]:
print(a*b)

[  50  200  450  800 1250]


In [29]:
print(a/b)

[2. 2. 2. 2. 2.]


In [30]:
print(a**2)

[ 100  400  900 1600 2500]


8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:

Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [31]:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])
salary

array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

In [32]:
salary.sum()

np.int64(290000)

In [33]:
salary.mean()

np.float64(36250.0)

In [34]:
salary.max()

np.int64(50000)

In [35]:
salary.min()

np.int64(25000)

In [36]:
np.median(salary)

np.float64(35000.0)

In [37]:
salary.std()

np.float64(8317.902379807063)

9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

Using NumPy boolean indexing, find:

Marks greater than 75
Marks between 50 and 80
Number of students who scored below 50
Percentage of students who scored 60 or above

Do not use a Python for loop.

In [38]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

In [39]:
print("Marks greater than 75:", marks[marks > 75])

print("Marks between 50 and 80:",
      marks[(marks >= 50) & (marks <= 80)])

print("Number of students who scored below 50:",
      np.sum(marks < 50))

print("Percentage of students who scored 60 or above:",
      np.mean(marks >= 60) * 100, "%")

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students who scored below 50: 3
Percentage of students who scored 60 or above: 60.0 %


10. The following array contains marks of four students in three subjects:

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

Calculate:

Total marks of each student
Average marks of each student
Average marks in each subject
Student with the highest total
Highest mark in each subject.

In [40]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])


In [42]:

# Total marks of each student
student_totals = marks.sum(axis=1)

# Average marks of each student
student_averages = marks.mean(axis=1)

# Average marks in each subject
subject_averages = marks.mean(axis=0)

# Student with highest total
highest_student = np.argmax(student_totals) + 1

# Highest mark in each subject
highest_subject_marks = marks.max(axis=0)

print("Total marks of each student:", student_totals)
print("Average marks of each student:", student_averages)
print("Average marks in each subject:", subject_averages)
print("Student with highest total: Student", highest_student)
print("Highest mark in each subject:", highest_subject_marks)

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with highest total: Student 3
Highest mark in each subject: [88 92 90]


11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

Matrix addition
Element-wise multiplication
Matrix multiplication
Transpose of A.

explain the difference between:
A * B and A @ B

In [43]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [44]:
print("Matrix Addition:")
print(A + B)



Matrix Addition:
[[ 6  8]
 [10 12]]


In [48]:
print("\nElement-wise Multiplication:")
print(A * B)



Element-wise Multiplication:
[[ 5 12]
 [21 32]]


In [49]:
print("\nMatrix Multiplication:")
print(A @ B)


Matrix Multiplication:
[[19 22]
 [43 50]]


In [50]:
print("\nTranspose of A:")
print(A.T)


Transpose of A:
[[1 3]
 [2 4]]


In [ ]:
#A * B multiplies matching elements together position-by-position

#A @ B performs traditional matrix multiplication by multiplying rows by columns.

12. Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

Find:

Mean temperature
Maximum and minimum temperatures
Number of days above the average temperature
Temperatures greater than 34°C
Difference between maximum and minimum
Standard deviation

In [51]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])


In [52]:
mean_temp = temperature.mean()
max_temp = temperature.max()
min_temp = temperature.min()
above_average = np.sum(temperature > mean_temp)
greater_34 = temperature[temperature > 34]
difference = max_temp - min_temp
std = temperature.std()

In [53]:
print("Mean temperature:", mean_temp)
print("Maximum temperature:", max_temp)
print("Minimum temperature:", min_temp)
print("Days above average:", above_average)
print("Temperatures greater than 34°C:", greater_34)
print("Difference:", difference)
print("Standard deviation:", std)

Mean temperature: 33.142857142857146
Maximum temperature: 37
Minimum temperature: 29
Days above average: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference: 8
Standard deviation: 2.356060357495806


13. Monthly sales of a company are:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

Determine:

Total annual sales
Average monthly sales
Month with the highest sales
Month with the lowest sales
Number of months with sales above ₹20,000
Percentage increase from January to December

Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.

In [54]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])


In [57]:
total_sales = sales.sum()
print(total_sales)

240000


In [58]:
average_sales = sales.mean()
print(average_sales)

20000.0


In [59]:
highest_month = sales.argmax() + 1
lowest_month = sales.argmin() + 1
print("Month with highest sales:", highest_month)
print("Month with lowest sales:", lowest_month)

Month with highest sales: 12
Month with lowest sales: 1


In [60]:
months_above_20000 = np.sum(sales > 20000)
print("Months with sales above ₹20,000:", months_above_20000)

Months with sales above ₹20,000: 6


In [61]:
percentage_increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Percentage increase January to December:", percentage_increase, "%")

Percentage increase January to December: 133.33333333333331 %


14. Consider marks of five students in four subjects:

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

Write a NumPy program that calculates:

Total marks of every student
Average of every student
Average mark for every subject
Highest-scoring student
Lowest-scoring student
Students whose average is greater than 80
Overall class average

Then assign a performance category based on average:

|  Average | Category          |
| -------: | ----------------- |
|     ≥ 85 | Excellent         |
| 70–84.99 | Good              |
| 50–69.99 | Average           |
|     < 50 | Needs Improvement |

Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

In [63]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

In [64]:
# Total marks
total = marks.sum(axis=1)

print("Total marks:", total)


Total marks: [341 275 366 235 316]


In [65]:
# Average marks of every student
average = marks.mean(axis=1)
print("Average marks:", average)



Average marks: [85.25 68.75 91.5  58.75 79.  ]


In [66]:
# Average mark for every subject
subject_average = marks.mean(axis=0)
print("Subject averages:", subject_average)



Subject averages: [74.  75.6 79.4 77.6]


In [67]:
# Highest-scoring student
highest_student = np.argmax(total) + 1

print("Highest-scoring student:", highest_student)


Highest-scoring student: 3


In [68]:
# Lowest-scoring student
lowest_student = np.argmin(total) + 1

print("Lowest-scoring student:", lowest_student)


Lowest-scoring student: 4


In [69]:
# Students with average > 80
students_above_80 = np.where(average > 80)[0] + 1

print("Students with average > 80:", students_above_80)


Students with average > 80: [1 3]


In [70]:
# Overall class average
class_average = marks.mean()

print("Overall class average:", class_average)


Overall class average: 76.65


In [71]:
# Performance categories
categories = np.select(
    [
        average >= 85,
        average >= 70,
        average >= 50
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Needs Improvement"
)
print("Performance categories:", categories)

Performance categories: ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


15. Generate 20 random integers between 1 and 100.

In [72]:
random_array = np.random.randint(1, 101, 20)

print(random_array)

[62 98 24 73 44 59 39  9 32 92 33 90 67  3 91 63 79 71 23 89]


16. Find all even numbers from the generated array.


In [73]:
even_numbers = random_array[random_array % 2 == 0]

print("Even numbers:", even_numbers)

Even numbers: [62 98 24 44 32 92 90]


17. Replace values below 50 with 0.

In [74]:
random_array[random_array < 50] = 0

print(random_array)

[62 98  0 73  0 59  0  0  0 92  0 90 67  0 91 63 79 71  0 89]


18. Sort the array in ascending and descending order.

In [75]:
ascending = np.sort(random_array)

descending = np.sort(random_array)[::-1]

print("Ascending order:", ascending)
print("Descending order:", descending)

Ascending order: [ 0  0  0  0  0  0  0  0 59 62 63 67 71 73 79 89 90 91 92 98]
Descending order: [98 92 91 90 89 79 73 71 67 63 62 59  0  0  0  0  0  0  0  0]


19. Find unique values and their frequencies.


In [76]:
unique_values, frequencies = np.unique(
    random_array,
    return_counts=True
)

print("Unique values:", unique_values)
print("Frequencies:", frequencies)

Unique values: [ 0 59 62 63 67 71 73 79 89 90 91 92 98]
Frequencies: [8 1 1 1 1 1 1 1 1 1 1 1 1]


20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.

In [77]:
matrix = np.random.random((5, 5))

print("Random matrix:")
print(matrix)

row_mean = matrix.mean(axis=1)
column_mean = matrix.mean(axis=0)

print("\nRow-wise means:")
print(row_mean)

print("\nColumn-wise means:")
print(column_mean)

Random matrix:
[[0.28357789 0.07115358 0.528601   0.95127695 0.08062413]
 [0.06786115 0.28624704 0.04756293 0.89285882 0.83054416]
 [0.08045311 0.31346862 0.77219841 0.08861732 0.8304557 ]
 [0.35398596 0.09130558 0.58924205 0.80996841 0.45300459]
 [0.80427961 0.62393397 0.01780943 0.23605315 0.16788655]]

Row-wise means:
[0.38304671 0.42501482 0.41703863 0.45950132 0.36999254]

Column-wise means:
[0.31803154 0.27722176 0.39108277 0.59575493 0.47250303]


21. Take your own example to normalize an array.

In [78]:
data = np.array([10, 20, 30, 40, 50])

normalized = (data - data.min()) / (data.max() - data.min())

print("Original array:", data)
print("Normalized array:", normalized)

Original array: [10 20 30 40 50]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


22. use your own data to standardize an array

In [80]:
data = np.array([10, 20, 30, 40, 50])

standardized = (data - data.mean()) / data.std()

print("Original array:", data)
print("Standardized array:", standardized)


Original array: [10 20 30 40 50]
Standardized array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.

In [81]:
marks = np.random.randint(0, 101, 100)
marks

array([ 81,  46,  79,  28,  56,  84,  85,  80,  93,  74,   2,  30,  16,
        30,  67,  77,  38,  81,  64,  71,  29,  52,  63,  50,  79,  48,
        17,  84,  16,  82,  67,  44,  92,  59,  86,  59,   2,  62,  46,
        78,  63,  92,   6,  93,  44,  53,  91,  42,  12,  34,   4,  53,
        96,  50,   1,  77,  84,  96,  54,  63,  17,  45,  18,  22,  56,
        54,  48,  29,  70,  55,  80,  57,  25,   4,  89,  66,  90,   9,
        49,  99,   3,  22,  44,  14,  69,  37,  65,  32,   9,  99,   9,
         1,  86,  34,   7,  10,   2,  66,  91, 100], dtype=int32)

In [82]:
range_0_39 = np.sum((marks >= 0) & (marks <= 39))
range_40_59 = np.sum((marks >= 40) & (marks <= 59))
range_60_79 = np.sum((marks >= 60) & (marks <= 79))
range_80_100 = np.sum((marks >= 80) & (marks <= 100))

print("Marks:", marks)

print("0-39:", range_0_39)
print("40-59:", range_40_59)
print("60-79:", range_60_79)
print("80-100:", range_80_100)

print(
    "Total:",
    range_0_39 + range_40_59 +
    range_60_79 + range_80_100
)

Marks: [ 81  46  79  28  56  84  85  80  93  74   2  30  16  30  67  77  38  81
  64  71  29  52  63  50  79  48  17  84  16  82  67  44  92  59  86  59
   2  62  46  78  63  92   6  93  44  53  91  42  12  34   4  53  96  50
   1  77  84  96  54  63  17  45  18  22  56  54  48  29  70  55  80  57
  25   4  89  66  90   9  49  99   3  22  44  14  69  37  65  32   9  99
   9   1  86  34   7  10   2  66  91 100]
0-39: 34
40-59: 23
60-79: 19
80-100: 24
Total: 100


24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.

In [83]:
import time

n = 1000000

# Python list
python_list = list(range(n))

start = time.time()

list_result = [x * 2 for x in python_list]

list_time = time.time() - start


# NumPy array
numpy_array = np.arange(n)

start = time.time()

numpy_result = numpy_array * 2

numpy_time = time.time() - start


print("Python list time:", list_time, "seconds")
print("NumPy array time:", numpy_time, "seconds")

Python list time: 0.030276060104370117 seconds
NumPy array time: 0.0016407966613769531 seconds
