In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv(
    r"C:\Users\omgow\OneDrive\Desktop\MSIS\AML_LAB\project_LAB_3\data\bestsellers.csv"
)

df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction


In [7]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction


In [8]:
df.tail()

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction


In [9]:
df.shape

(550, 7)

In [10]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [11]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [12]:
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews        float64
Price          float64
Year             int64
Genre           object
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(3), int64(1), object(3)
memory usage: 30.2+ KB


In [14]:
df.describe()

,User Rating,Reviews,Price,Year
count,548.000000,549.000000,549.000000,550.000000
mean,4.618066,11958.038251,13.100182,2014.000000
std,0.227341,11741.299889,10.852149,3.165156
min,3.300000,37.000000,0.000000,2009.000000
25%,4.500000,4028.000000,7.000000,2011.000000
50%,4.700000,8580.000000,11.000000,2014.000000
75%,4.800000,17323.000000,16.000000,2017.000000
max,4.900000,87841.000000,105.000000,2019.000000


In [15]:
df.isnull().sum()

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [27]:
#split independent variables
# Select independent variables
x = df[
    ["User Rating", "Reviews", "Price", "Year"]
].values

x

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]])

In [28]:
#split dependent variables
# Select dependent variable
y = df["Genre"].values

y

array(['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non F

In [29]:
#taking care of missing values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:, 2:5])
x[:, 2:5]=imputer.transform(x[:, 2:5])
x

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]])

In [30]:
#encoding categorical data
#encoding the independent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x=LabelEncoder()
x[:, 0]=labelencoder_x.fit_transform(x[:, 0])
x[:, 1]=labelencoder_x.fit_transform(x[:, 1])
print(x)

[[  11.  291.    8. 2016.]
 [  10.   52.   22. 2011.]
 [  11.  296.   15. 2018.]
 ...
 [  11.  277.    8. 2017.]
 [  11.  277.    8. 2018.]
 [  11.  277.    8. 2019.]]


In [31]:
## Encoding the dependent variable

from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

print(y)

[1 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0
 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 1
 1 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0
 1 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 1
 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0
 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0
 0 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1
 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 0 0 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0
 0 0 1 1 1 0 0 0 0 0 0 1 

In [33]:
#split data into training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [34]:
x_test

array([[1.000e+01, 3.010e+02, 8.000e+00, 2.009e+03],
       [1.200e+01, 3.320e+02, 1.600e+01, 2.010e+03],
       [1.100e+01, 2.510e+02, 5.000e+00, 2.018e+03],
       [1.300e+01, 2.970e+02, 5.000e+00, 2.013e+03],
       [9.000e+00, 1.100e+01, 1.000e+00, 2.009e+03],
       [1.100e+01, 1.170e+02, 1.500e+01, 2.016e+03],
       [1.300e+01, 2.150e+02, 1.000e+01, 2.017e+03],
       [1.000e+01, 1.810e+02, 4.000e+00, 2.013e+03],
       [1.200e+01, 2.940e+02, 5.000e+00, 2.014e+03],
       [1.200e+01, 1.090e+02, 1.600e+01, 2.018e+03],
       [1.200e+01, 6.800e+01, 1.700e+01, 2.013e+03],
       [1.100e+01, 3.150e+02, 6.000e+00, 2.015e+03],
       [9.000e+00, 3.000e+00, 1.500e+01, 2.009e+03],
       [1.100e+01, 3.100e+02, 1.100e+01, 2.012e+03],
       [1.200e+01, 2.520e+02, 5.000e+00, 2.016e+03],
       [7.000e+00, 4.800e+01, 8.000e+00, 2.010e+03],
       [7.000e+00, 2.710e+02, 1.000e+01, 2.012e+03],
       [1.100e+01, 3.200e+02, 1.100e+01, 2.016e+03],
       [8.000e+00, 9.100e+01, 9.000e+00, 2.009

In [35]:
#FEATURE SCALING
#sc_X=(x[1]-mean) / standrad deviation
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)       #fit_tranfrom is not needed for test data as we are not learning

In [36]:
x_train

array([[ 0.7603164 ,  1.15270389, -0.66655664,  1.24974319],
       [ 0.7603164 ,  0.79125742, -0.85564462,  0.93801586],
       [ 0.7603164 ,  0.16876629, -0.76110063,  1.56147051],
       ...,
       [-0.99810261,  0.84145832,  0.08979526,  0.62628854],
       [ 0.7603164 ,  1.08242263, -0.38292468,  0.93801586],
       [ 0.32071165,  0.24908773, -0.38292468, -0.62062077]])