In [1]:
!pip install pandas

   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/10.0 MB 6.7 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/10.0 MB 9.1 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/10.0 MB 8.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/10.0 MB 8.6 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/10.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 8.6 MB/s  0:00:01

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ----------


[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install matplotlib


  Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Using cached matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)

   ---------------------------------------- 0/7 [pyparsing]
   -


[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df=pd.read_csv("D:\AML_0024\project\data\data.csv")

<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
C:\Users\MSIS\AppData\Local\Temp\ipykernel_12320\1938746916.py:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
  df=pd.read_csv("D:\AML_0024\project\data\data.csv")


In [22]:
df


,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [23]:
df.head()


,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [24]:
#df=pd.read_excel("../data/data.excel,sheet_name="sheet1""")#this for excel dataset with multiple sheets

In [25]:
df.tail()

,Country,Age,Salary,Purchased
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [26]:
df.shape

(10, 4)

In [27]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [28]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     str    
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str    
dtypes: float64(2), str(2)
memory usage: 452.0 bytes


In [30]:
df.describe()

,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [32]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [37]:
#split independent variables
#loc uses labels
#iloc uses integer positions (numbers from 0 to the length of the data)
df
x=df.iloc[:,:-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [38]:
#split dependent variables
y=df.iloc[:,3].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [42]:
%pip install scikit-learn

   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.3 MB 7.5 MB/s eta 0:00:01
   ------------ --------------------------- 2.6/8.3 MB 7.4 MB/s eta 0:00:01
   ------------------ --------------------- 3.9/8.3 MB 6.9 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.3 MB 6.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 6.7 MB/s  0:00:01
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   - -------------------------------------- 1.3/37.3 MB 7.6 MB/s eta 0:00:05
   --- ------------------------------------ 2.9/37.3 MB 7.6 MB/s eta 0:00:05
   ---- ----------------------------------- 4.5/37.3 MB 7.3 MB/s eta 0:00:05
   ------ --------------------------------- 5.8/37.3 MB 7.1 MB/s eta 0:00:05
   ------- -------------


[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [44]:
#taking care of missing values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [45]:
#encoding categorical data
#encoding the independent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x=LabelEncoder()
x[:, 0]=labelencoder_x.fit_transform(x[:, 0])
print(x)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [46]:
## Encoding the dependent variable

from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


In [49]:
#encoding independent variable
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("Country", OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)

x.astype(int)

array([[    1,     0,     1,     0,     0,    44, 72000],
       [    0,     1,     0,     0,     1,    27, 48000],
       [    0,     1,     0,     1,     0,    30, 54000],
       [    0,     1,     0,     0,     1,    38, 61000],
       [    0,     1,     0,     1,     0,    40, 63777],
       [    1,     0,     1,     0,     0,    35, 58000],
       [    0,     1,     0,     0,     1,    38, 52000],
       [    1,     0,     1,     0,     0,    48, 79000],
       [    0,     1,     0,     1,     0,    50, 83000],
       [    1,     0,     1,     0,     0,    37, 67000]])

In [50]:
#split data into training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [52]:
x_test

array([[0.0, 1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [53]:
x_test.astype(int)

array([[    0,     1,     0,     1,     0,    30, 54000],
       [    0,     1,     0,     1,     0,    40, 63777]])

In [57]:
#FEATURE SCALING
#sc_X=(x[1]-mean) / standrad deviation
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)       #fit_tranfrom is not needed for test data as we are not learning

In [58]:
x_train

array([[-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
        -1.82709535, -1.45240802],
       [-1.        ,  1.        , -1.        ,  2.64575131, -0.77459667,
         1.47603773,  1.53784378],
       [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
        -0.39095053,  0.17087153],
       [-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
        -0.1356359 , -1.11066496],
       [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
        -0.6781795 , -0.59805036],
       [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
         1.18880877,  1.19610072],
       [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
         0.61435084,  0.59805036],
       [-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
        -0.24733605, -0.34174306]])